wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.9
    session_history: code/_session_history.ipynb
    start_time: 1639244925
    t:
      3:
      - 2
      4: 3.9.9
      5: 0.12.7
      8:
      - 1
      - 5
